language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./public
  skip_cleanup: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "jest --verbose -u"
after_success:
  - "npm run deploy"
