language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - "jest --verbose -u"
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  # Note you will need the following env variables 
  # NETLIFY_SITE_ID NETLIFY_AUTH_TOKEN
  script: netlify deploy -s $NETLIFY_SITE_ID 
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: $SLACK_PROJECT:$TRAVIS_ACCESS_TOKEN
