language: node_js
node_js: node
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
    - node_modules
  overides:
    - npm ci
    - npm run cy:verify

script:
  - "yarn run test:jest:ci"
  - "yarn run test:e2e:ci"
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  # Note you will need the following env variables 
  # NETLIFY_SITE_ID NETLIFY_AUTH_TOKEN
  script: netlify deploy -s $NETLIFY_SITE_ID 
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: $SLACK_PROJECT:$TRAVIS_ACCESS_TOKEN
