language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: script
  script: chmod +x .scripts/publish.sh && ./scripts/publish.sh
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "jest --verbose -u"
after_success:
  - "npm run deploy"
